# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jwtlogin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234

    url: jdbc:mysql://moviedb.cmpx1qstwkzp.ap-northeast-2.rds.amazonaws.com:3306/testPy0o0?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: moviedatabase


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
